<?php

namespace AppBundle\Repository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtFormRepository extends \Doctrine\ORM\EntityRepository
{
}
